# Generated by Django 4.1.4 on 2022-12-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=255, verbose_name='Country')),
                ('Confirmed', models.CharField(max_length=255)),
                ('Deaths', models.CharField(max_length=255)),
                ('Recovered', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
