# Generated by Django 4.1.4 on 2022-12-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19', '0001_initial'),
    ]

    operations = [
    ]
